FROM postgres:9.4

ARG ROOT=/
ARG APP_DIR=/app

WORKDIR $ROOT

# Install git
RUN apt-get update && \
    apt-get install -y git && \
    apt-get clean;

ADD ./backup_database.sh /backup_database.sh
# RUN chmod 0644 /backup_database.sh

RUN mkdir $APP_DIR


WORKDIR $APP_DIR
RUN git clone -b development https://github.com/MetaCell/scidash
RUN cp scidash/service/scripts/db-create-psql.sh /docker-entrypoint-initdb.d/db-create-psql.sh