FROM scidash_virgo:latest

USER root 

# BUILD VARIABLES
ARG ROOT=/
ARG APP_DIR=/app
ARG NRN_SYMLINK=/Applications/NEURON-7.6/nrn/
ARG DOTENV_FILE=env-docker
ARG STATIC_DIR=$APP_DIR/scidash/static
ARG GEPPETTO_DIR=$STATIC_DIR/org.geppetto.frontend/src/main/webapp
ARG SCIDASH_BRANCH=development
ENV SERVER_HOME $APP_DIR/virgo-tomcat-server

WORKDIR $ROOT

#COPYING PROJECT
WORKDIR $APP_DIR
RUN git clone -b $SCIDASH_BRANCH https://github.com/MetaCell/scidash

# INSTALLING REQUIREMENTS
RUN apt-get install -y curl wget lsof
RUN curl -sL https://deb.nodesource.com/setup_9.x | bash
RUN apt-get update && apt-get -y install nodejs

WORKDIR $APP_DIR/scidash
RUN pip install virtualenv 
RUN virtualenv venv-py2 -p python2.7

RUN make install-backend-with-env
RUN make install-sciunit-neuronunit
RUN make install-frontend

WORKDIR $GEPPETTO_DIR
RUN ls -la
RUN npm run build-dev-noTest

WORKDIR /nrn
RUN chown -R developer ./
WORKDIR $APP_DIR/scidash
RUN chown -R developer ./
RUN cp ./service/dotenv/scidash_env .env

USER developer

CMD ./service/scripts/run.sh
