FROM ubuntu:16.04

RUN add-apt-repository ppa:jonathonf/python-3.6
RUN apt-get update && apt-get install python3.6

# BUILD VARIABLES
ARG ROOT=/
ARG APP_DIR=/app
ARG DOTENV_FILE=env-docker
ARG VENV_PATH=./venv/
ARG STATIC_DIR=$APP_DIR/static
ARG GEPPETTO_DIR=$STATIC_DIR/org.geppetto.frontend/src/main/webapp

WORKDIR $ROOT

# PYTHON INSTALL
RUN pip install virtualenv
#ENV PATH $VENV_PATH/bin:$PATH
ENV PYTHONUNBUFFERED 1

# CREATING PROJECT FOLDERS
RUN mkdir $APP_DIR

#COPYING PROJECT
WORKDIR $APP_DIR
ADD . $APP_DIR

RUN apt-get -y install software-properties-common

# INSTALL JAVA
RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer --allow-unauthenticated && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer

ENV JAVA_HOME /usr/lib/jvm/java-8-oracle

# INSTALLING REQUIREMENTS
RUN apt-get install curl
RUN curl -sL https://deb.nodesource.com/setup_9.x | bash
RUN apt-get update && apt-get install nodejs


RUN make install-backend-with-env
RUN make install-sciunit-neuronunit

WORKDIR $GEPPETTO_DIR
RUN npm run build-dev-noTest

WORKDIR $APP_DIR
COPY ./service/dotenv/env-docker $APP_DIR/.env

CMD ./service/scripts/run.sh
