# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-10 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='prediction',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testinstance',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
