# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-15 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0002_auto_20171226_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinstance',
            name='build_info',
            field=models.CharField(blank=True, default=b'', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='hostname',
            field=models.CharField(blank=True, default=b'', max_length=200, null=True),
        ),
    ]
