# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-10 11:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0002_auto_20171110_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='unpicklable',
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='observation',
            field=django.contrib.postgres.fields.hstore.HStoreField(),
        ),
    ]
