# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 09:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0003_auto_20171110_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='unpicklable',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=[], size=None),
        ),
    ]
