# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-13 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0004_testinstance_unpicklable'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='verbose',
            field=models.IntegerField(default=0),
        ),
    ]
