# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 14:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0006_auto_20171114_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testclass',
            name='build_info',
        ),
        migrations.RemoveField(
            model_name='testclass',
            name='hostname',
        ),
        migrations.RemoveField(
            model_name='testclass',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='testinstance',
            name='build_info',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='testinstance',
            name='hostname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='testinstance',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 15, 14, 28, 57, 567906)),
        ),
        migrations.AlterField(
            model_name='score',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 15, 14, 28, 57, 568860)),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 15, 14, 28, 57, 566755)),
        ),
    ]
