# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 17:13
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sciunittests', '0007_auto_20171115_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testsuite',
            name='owmer',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='score',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 16, 17, 13, 12, 645167)),
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 16, 17, 13, 12, 644347)),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 16, 17, 13, 12, 643032)),
        ),
    ]
