# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0008_auto_20180124_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='hash',
            field=models.CharField(blank=True, max_length=57, null=True, unique=True),
        ),
    ]
