# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 15:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0008_auto_20171116_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsuite',
            old_name='owmer',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='score',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 15, 56, 15, 993969)),
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 15, 56, 15, 993138)),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 20, 15, 56, 15, 991800)),
        ),
    ]
