# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 18:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0009_auto_20171120_1556'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testinstance',
            name='test_suite',
        ),
        migrations.RemoveField(
            model_name='testinstance',
            name='unpicklable',
        ),
        migrations.AddField(
            model_name='testinstance',
            name='test_suites',
            field=models.ManyToManyField(to='sciunittests.TestSuite'),
        ),
        migrations.AlterField(
            model_name='score',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 18, 12, 45, 28965)),
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 18, 12, 45, 27088)),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 18, 12, 45, 25495)),
        ),
    ]
