# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0009_testsuite_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuite',
            name='hash',
            field=models.CharField(blank=True, max_length=57, null=True),
        ),
    ]
