# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 18:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0010_auto_20171122_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 18, 25, 58, 193335, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 18, 25, 58, 191826, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 22, 18, 25, 58, 190548, tzinfo=utc)),
        ),
    ]
