# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0011_auto_20180309_1229'),
        ('sciunittests', '0009_merge_20180205_1233'),
    ]

    operations = [
    ]
