# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 19:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0012_auto_20171122_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testsuite',
            name='build_info',
        ),
        migrations.RemoveField(
            model_name='testsuite',
            name='hostname',
        ),
    ]
