# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-25 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0016_scoreinstance_score_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreclass',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
