# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-05-25 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0018_testinstance_hash_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreinstance',
            name='hash_id',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testclass',
            name='url',
            field=models.URLField(blank=True, default='', null=True, unique=True),
        ),
    ]
