# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-12 16:34
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0019_auto_20180525_1008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreinstance',
            name='related_data',
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='observation',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
