# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 11:55
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sciunitmodels', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0)),
                ('prediction', models.FloatField(default=0)),
                ('related_data', django.contrib.postgres.fields.hstore.HStoreField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('model_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sciunitmodels.ModelInstance')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Test class',
                'verbose_name_plural': 'Test classes',
            },
        ),
        migrations.CreateModel(
            name='TestInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', django.contrib.postgres.fields.hstore.HStoreField()),
                ('description', models.TextField(blank=True, null=True)),
                ('verbose', models.IntegerField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('hostname', models.CharField(default='', max_length=200)),
                ('build_info', models.CharField(default='', max_length=200)),
                ('test_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sciunittests.TestClass')),
            ],
            options={
                'verbose_name': 'Test instance',
                'verbose_name_plural': 'Test instances',
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Test suite',
                'verbose_name_plural': 'Test suites',
            },
        ),
        migrations.AddField(
            model_name='testinstance',
            name='test_suites',
            field=models.ManyToManyField(to='sciunittests.TestSuite'),
        ),
        migrations.AddField(
            model_name='score',
            name='test_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sciunittests.TestInstance'),
        ),
    ]
