# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-26 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='_class',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='score_key',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testclass',
            name='url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
