# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 14:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0003_auto_20180115_1232'),
        ('sciunittests', '0003_auto_20171226_1757'),
    ]

    operations = [
    ]
