# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0004_auto_20180118_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score_key',
            new_name='sort_key',
        ),
    ]
