# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-19 15:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0005_auto_20180118_1516'),
        ('sciunittests', '0004_merge_20180119_1445'),
    ]

    operations = [
    ]
