# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0006_auto_20180123_1151'),
        ('sciunittests', '0006_merge_20180119_1504'),
    ]

    operations = [
    ]
