# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-05 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0007_merge_20180123_1527'),
        ('sciunittests', '0008_auto_20180124_2257'),
    ]

    operations = [
    ]
