# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 15:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0012_merge_20180309_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='score',
            name='prediction',
        ),
        migrations.AddField(
            model_name='score',
            name='prediction_dict',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='score',
            name='prediction_numeric',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
