# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0012_merge_20180309_1254'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-timestamp']},
        ),
    ]
