# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-17 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0015_auto_20180416_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreinstance',
            name='score_class',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sciunittests.ScoreClass'),
            preserve_default=False,
        ),
    ]
