# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-03 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0020_auto_20180812_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreinstance',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
