# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-19 13:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def populate_user_data(apps, schema_editor):
    if hasattr(settings, 'POPULATE_USERS'):
        if not settings.POPULATE_USERS:
            return
    else:
        return

    ScidashUser = apps.get_model('general', 'ScidashUser')
    db_alias = schema_editor.connection.alias

    users = ScidashUser.objects.using(db_alias).all()

    justasb_user = None
    openworm_user = None

    ricks_tests = [
        'head_tip_speed_absTest',
        'max_amplitudeTest',
        'lengthTest',
        'midbody_speed_absTest',
        'midbody_bend_mean_absTest'
    ]

    for user in users:
        if user.username == 'justasb':
            justasb_user = user
        if user.username == 'openworm':
            openworm_user = user

    TestInstance = apps.get_model('sciunittests', 'TestInstance')

    tests = TestInstance.objects.using(db_alias).all()

    for test in tests:
        if test.owner is not None:
            continue

        if test.test_class.class_name in ricks_tests:
            test.owner = openworm_user
        else:
            test.owner = justasb_user

        test.save()


def unpopulate_user_data(apps, schema_editor):
    # Data will be removed with field so just
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sciunittests', '0021_auto_20181203_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(populate_user_data, unpopulate_user_data)
    ]
