# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-31 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0023_auto_20190131_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinstance',
            name='test_suites',
            field=models.ManyToManyField(blank=True, null=True, related_name='tests', to='sciunittests.TestSuite'),
        ),
    ]
