# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-31 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0024_auto_20190131_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='name',
            field=models.CharField(default='Default Name', max_length=200),
        ),
    ]
