# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-12 14:43
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0026_auto_20190206_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='testclass',
            name='import_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testclass',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testclass',
            name='observation_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
