# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-13 13:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0027_auto_20190212_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='testclass',
            name='test_parameters_schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
