# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-15 11:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0028_testclass_test_parameters_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='observation',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
