# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-04 09:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0029_auto_20190215_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='testclass',
            name='units',
            field=models.TextField(blank=True, null=True),
        ),
    ]
