# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-25 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0031_scoreinstance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreinstance',
            name='score_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sciunittests.ScoreClass'),
        ),
        migrations.AlterField(
            model_name='scoreinstance',
            name='status',
            field=models.CharField(choices=[('s', 'Scheduled'), ('c', 'Calculated'), ('l', 'Locked')], default='c', max_length=3),
        ),
    ]
