# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-04-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0035_remove_scoreinstance_bool_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='testinstance',
            name='status',
            field=models.CharField(choices=[('l', 'Locked'), ('a', 'Available')], default='a', max_length=2),
        ),
    ]
