# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-20 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0041_auto_20190513_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreinstance',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scoreinstance',
            name='status',
            field=models.CharField(choices=[('s', 'Scheduled'), ('c', 'Calculated'), ('l', 'Locked'), ('f', 'Failed')], default='c', max_length=3),
        ),
    ]
