# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-27 14:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0042_auto_20190520_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsuite',
            old_name='hash',
            new_name='_hash',
        ),
    ]
