# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-27 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0043_auto_20190527_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testsuite',
            old_name='_hash',
            new_name='hash',
        ),
    ]
