# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-06-23 13:49
from __future__ import unicode_literals

from django.db import migrations
from scidash.sciunittests.models import TestClass


def populate_classes(apps, schema_editor):
    data = [
        {
            'class_name': 'VmTest',
            'import_path': 'neuronunit.tests.base.VmTest'
        },
        {
            'class_name': 'FakeTest',
            'import_path': 'neuronunit.tests.base.FakeTest'
        },
        {
            'class_name': 'IVCurveSSTest',
            'import_path': 'neuronunit.tests.channel.IVCurveSSTest'
        },
        {
            'class_name': 'IVCurvePeakTest',
            'import_path': 'neuronunit.tests.channel.IVCurvePeakTest'
        },
        {
            'class_name': 'IVCurvePeakTest',
            'import_path': 'neuronunit.tests.channel.IVCurvePeakTest'
        },
        {
            'class_name': 'Druckmann2013Test',
            'import_path': 'neuronunit.tests.druckmann2013.Druckmann2013Test'
        },
        {
            'class_name': 'AP12AmplitudeDropTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP12AmplitudeDropTest'
        },
        {
            'class_name': 'AP1SSAmplitudeChangeTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP1SSAmplitudeChangeTest'
        },
        {
            'class_name': 'AP1AmplitudeTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP1AmplitudeTest'
        },
        {
            'class_name': 'AP1WidthHalfHeightTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP1WidthHalfHeightTest'
        },
        {
            'class_name': 'AP1WidthPeakToThroughTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP1WidthPeakToThroughTest'
        },
        {
            'class_name': 'AP1RateOfChangePeakToThroughTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP1RateOfChangePeakToThroughTest'
        },
        {
            'class_name': 'AP1AHPDepthTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP1AHPDepthTest'
        },
        {
            'class_name': 'AP12AmplitudeChangePercentTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP12AmplitudeChangePercentTest'
        },
        {
            'class_name': 'AP12HalfWidthChangePercentTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP12HalfWidthChangePercentTest'
        },
        {
            'class_name': 'AP12RateOfChangePeakToTroughPercentChangeTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP12RateOfChangePeakToTroughPercentChangeTest'
        },
        {
            'class_name': 'AP12AHPDepthPercentChangeTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP12AHPDepthPercentChangeTest'
        },
        {
            'class_name': 'InputResistanceTest',
            'import_path': 'neuronunit.tests.druckmann2013.InputResistanceTest'
        },
        {
            'class_name': 'AP1DelayMeanTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP1DelayMeanTest'
        },
        {
            'class_name': 'AP1DelaySDTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP1DelaySDTest'
        },
        {
            'class_name': 'AP2DelayMeanTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP2DelayMeanTest'
        },
        {
            'class_name': 'AP2DelaySDTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP2DelaySDTest'
        },
        {
            'class_name': 'Burst1ISIMeanTest',
            'import_path': 'neuronunit.tests.druckmann2013.Burst1ISIMeanTest'
        },
        {
            'class_name': 'Burst1ISISDTest',
            'import_path': 'neuronunit.tests.druckmann2013.Burst1ISISDTest'
        },
        {
            'class_name': 'InitialAccommodationMeanTest',
            'import_path': 'neuronunit.tests.druckmann2013.InitialAccommodationMeanTest'
        },
        {
            'class_name': 'SSAccommodationMeanTest',
            'import_path': 'neuronunit.tests.druckmann2013.SSAccommodationMeanTest'
        },
        {
            'class_name': 'AccommodationRateToSSTest',
            'import_path': 'neuronunit.tests.druckmann2013.AccommodationRateToSSTest'
        },
        {
            'class_name': 'AccomodationAtSSMeanTest',
            'import_path': 'neuronunit.tests.druckmann2013.AccomodationAtSSMeanTest'
        },
        {
            'class_name': 'AccomodationRateMeanAtSSTest',
            'import_path': 'neuronunit.tests.druckmann2013.AccomodationRateMeanAtSSTest'
        },
        {
            'class_name': 'AccomodationRateMeanAtSSTest',
            'import_path': 'neuronunit.tests.druckmann2013.AccomodationRateMeanAtSSTest'
        },
        {
            'class_name': 'ISICVTest',
            'import_path': 'neuronunit.tests.druckmann2013.ISICVTest'
        },
        {
            'class_name': 'ISIMedianTest',
            'import_path': 'neuronunit.tests.druckmann2013.ISIMedianTest'
        },
        {
            'class_name': 'ISIBurstMeanChangeTest',
            'import_path': 'neuronunit.tests.druckmann2013.ISIBurstMeanChangeTest'
        },
        {
            'class_name': 'SpikeRateStrongStimTest',
            'import_path': 'neuronunit.tests.druckmann2013.SpikeRateStrongStimTest'
        },
        {
            'class_name': 'AP1DelayMeanStrongStimTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP1DelayMeanStrongStimTest'
        },
        {
            'class_name': 'AP1DelaySDSTrongStimTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP1DelaySDSTrongStimTest'
        },
        {
            'class_name': 'AP2DelayMeanStrongStimTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP2DelayMeanStrongStimTest'
        },
        {
            'class_name': 'AP2DelaySDStrongStimTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP2DelaySDStrongStimTest'
        },
        {
            'class_name': 'Burst1ISIMeanStrongStimTest',
            'import_path': 'neuronunit.tests.druckmann2013.Burst1ISIMeanStrongStimTest'
        },
        {
            'class_name': 'Burst1ISISDStrongStimTest',
            'import_path': 'neuronunit.tests.druckmann2013.AP2DelaySDStrongStimTest'
        },
        {
            'class_name': 'TFRTypeTest',
            'import_path': 'neuronunit.tests.dynamics.TFRTypeTest'
        },
        {
            'class_name': 'BurstinessTest',
            'import_path': 'neuronunit.tests.dynamics.BurstinessTest'
        },
        {
            'class_name': 'ISICVTest',
            'import_path': 'neuronunit.tests.dynamics.ISICVTest'
        },
        {
            'class_name': 'ISITest',
            'import_path': 'neuronunit.tests.dynamics.ISITest'
        },
        {
            'class_name': 'LocalVariationTest',
            'import_path': 'neuronunit.tests.dynamics.LocalVariationTest'
        },
        {
            'class_name': 'LocalVariationTest',
            'import_path': 'neuronunit.tests.dynamics.LocalVariationTest'
        },
        {
            'class_name': 'RheobaseTest',
            'import_path': 'neuronunit.tests.fi.RheobaseTest'
        },
        {
            'class_name': 'RheobaseTestP',
            'import_path': 'neuronunit.tests.fi.RheobaseTestP'
        },
        {
            'class_name': 'MorphologyTest',
            'import_path': 'neuronunit.tests.morphology.MorphologyTest'
        },
    ]


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0044_auto_20190527_1408'),
    ]

    operations = [
    ]
