# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-12 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0044_auto_20190527_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreinstance',
            name='model_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='sciunitmodels.ModelInstance'),
        ),
        migrations.AlterField(
            model_name='scoreinstance',
            name='test_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='sciunittests.TestInstance'),
        ),
        migrations.AlterField(
            model_name='scoreinstance',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
