# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-11 01:56
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import scidash.sciunittests.models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0045_auto_20190712_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='testclass',
            name='default_params',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, encoder=scidash.sciunittests.models.JSONEncoder, null=True),
        ),
        migrations.AlterField(
            model_name='scoreinstance',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='testinstance',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
