# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-12-19 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0046_auto_20190827_0221'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scoreinstance',
            index=models.Index(fields=['-timestamp'], name='sciunittest_timesta_aa7614_idx'),
        ),
    ]
