# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-03 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunittests', '0047_auto_20191219_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreinstance',
            name='related_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
