version: '3'

services:
  scidash-redis:
    image: redis
  scidash-postgres:
    image: metacell/scidash-db
  scidash:
    image: metacell/scidash
    ports:
        - 8000:8000
    depends_on:
        - scidash-redis
        - scidash-postgres

