version: '2'

services:
  scidash-redis:
    image: redis
  scidash-postgres:
    image: metacell/scidash-db
  scidash:
    image: metacell/scidash:0.1.3
    ports:
        - 80:8000
    depends_on:
        - scidash-redis
        - scidash-postgres

