version: '2'

services:
  scidash-redis:
    image: redis
  scidash-postgres:
    image: metacell/scidash-db
    ports:
        - 5432:5432
  scidash:
    image: metacell/scidash:3.1.0
    ports:
        - 80:8000
    depends_on:
        - scidash-redis
        - scidash-postgres

