apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: scidash-postgres
  name: scidash-postgres
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: scidash-postgres
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: scidash-postgres
    spec:
      containers:
      - image: {{REGISTRY_URL}}/scidash_db:production
        imagePullPolicy: Always
        name: scidash-postgres
        ports:
        - containerPort: 5432
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 40
---
apiVersion: v1
kind: Service
metadata:
  name: scidash-postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: scidash-postgres