apiVersion: v1
kind: Deployment
metadata:
  name: scidash-dev
  labels:
    app: scidash-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: scidash-dev
    spec:
      containers:
      - name: scidash
        image: r.cfcr.io/tarelli/metacell/scidash:development
        imagePullPolicy: Always
        ports:
        - containerPort: 8000

        volumeMounts:
          name: scidash-secret
          mountPath: "/scidash-secret"
          readOnly: true

        env:
          name: DB_USER
          valueFrom:
            secretKeyRef:
              name: scidash-secret
              key: DB_USER
          name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: scidash-secret
              key: DB_PASSWORD

      - name: scidash-redis
        image: redis
        imagePullPolicy: Always
        ports:
        - containerPort: 6379

    volumes:
      - name: scidash-secret
        secret:
          secretName: scidash-secret
