# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-04 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_auto_20180403_1533'),
        ('general', '0005_auto_20180404_1607'),
    ]

    operations = [
    ]
