# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-03 21:06
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_order', models.PositiveIntegerField(default=0)),
                ('content', ckeditor.fields.RichTextField()),
            ],
            options={
                'ordering': ['content_order'],
            },
        ),
    ]
