# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-03 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('general', '0008_contentitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='name',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
    ]
