# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-05 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_contentitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentitem',
            name='display_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentitem',
            name='display_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
