# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-16 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_auto_20200305_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='scidashuser',
            name='show_instructions',
            field=models.BooleanField(default=True),
        ),
    ]
