# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-20 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logfile',
            name='rows_amount',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='logfile',
            name='path',
            field=models.FilePathField(allow_folders=True, match='.*\\.log$', path='/Users/roman/Projects/metacell/scidash', recursive=True),
        ),
    ]
