# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-03 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logviewer', '0002_auto_20190520_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logfile',
            name='path',
            field=models.FilePathField(allow_folders=True, match='.*\\.log$', path='/opt/projects/metacell/scidash_new', recursive=True),
        ),
    ]
