# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-06 19:29
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('models', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('related_data', django.contrib.postgres.fields.hstore.HStoreField()),
                ('unpicklable', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), size=None)),
                ('model_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.ModelInstance')),
            ],
        ),
        migrations.CreateModel(
            name='TestClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Test class',
                'verbose_name_plural': 'Test classes',
            },
        ),
        migrations.CreateModel(
            name='TestInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(max_length=50)),
                ('test_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.TestClass')),
            ],
            options={
                'verbose_name': 'Test instance',
                'verbose_name_plural': 'Test instances',
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Test suite',
                'verbose_name_plural': 'Test suites',
            },
        ),
        migrations.AddField(
            model_name='score',
            name='test_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.TestInstance'),
        ),
    ]
