# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-01 15:40
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciunitmodels', '0003_auto_20180227_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelinstance',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
