# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-06 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sciunitmodels', '0007_auto_20180525_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelinstance',
            name='timestamp',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
