# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-31 13:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciunitmodels', '0010_auto_20190131_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelinstance',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
