# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-18 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunitmodels', '0011_auto_20190131_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelclass',
            name='import_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
