# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-22 10:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunitmodels', '0013_auto_20190221_1626'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capabilitymodelthrough',
            options={'verbose_name': 'Capabilities with extra check', 'verbose_name_plural': 'Capabilities with extra checks'},
        ),
        migrations.AlterField(
            model_name='modelclass',
            name='capabilities',
            field=models.ManyToManyField(blank=True, related_name='capabilities', to='sciunitmodels.Capability'),
        ),
        migrations.AlterField(
            model_name='modelclass',
            name='extra_capabilities',
            field=models.ManyToManyField(blank=True, related_name='capabilities_with_check', through='sciunitmodels.CapabilityModelThrough', to='sciunitmodels.Capability'),
        ),
    ]
