# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-02-28 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunitmodels', '0014_auto_20190222_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelclass',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
