# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-05-10 12:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sciunitmodels', '0017_modelinstance_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CapabilityModelThrough',
            new_name='ExtraCapabilityModelThrough',
        ),
    ]
