# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-07-12 10:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunitmodels', '0020_auto_20190510_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelinstance',
            name='timestamp',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
