# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-03-03 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sciunitmodels', '0021_auto_20190712_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelclass',
            name='import_path',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='modelinstance',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
